version: "3.9"

services:
  app:
    build: .
    container_name: node_api_prod
    ports:
      - "9000:9000"
    env_file:
      - .env.production
    depends_on:
      - mongo
    restart: always
    command: npm start

  mongo:
    image: mongo
    container_name: mongodb_prod
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_prod_data:/data/db
    restart: always

volumes:
  mongo_prod_data: