version: "3.9"

services:
  app:
    build: .
    container_name: node_api_dev
    ports:
      - "9000:9000"
    env_file:
      - .env.development
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
    command: npm run dev

  mongo:
    image: mongo
    container_name: mongodb_dev
    ports:
      - "27017:27017"
    volumes:
      - mongo_dev_data:/data/db

volumes:
  mongo_dev_data: